alias la='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ali='vim ~/.bash_aliases'
alias h='cd $HOME'
alias d='cd ~/Desktop'
alias c='clear'
alias clas='xprop'

# second monitor setup
alias m1='xrandr --output HDMI-1 --auto  --right-of eDP-1 --auto'
alias m2='xrandr --output eDP-1 --off'
alias m2o='xrandr --output eDP-1 --auto'
alias conv='echo convert -resize 1024X768  source.png dest.jpg'

# UTM
alias asdn='cd /home/mira/Desktop/UTM/ASDN'
alias log='wine /home/mira/Desktop/UTM/ASDN/LogicWorks/Program/LogicWorks.exe &'
alias lfa='cd /home/mira/Desktop/UTM/LFA'
alias lfal='cd /home/mira/Desktop/UTM/LFA/labs'
alias ap='cd /home/mira/Desktop/UTM/APA'
alias apl='cd /home/mira/Code/APA'
alias cde='cd /home/mira/Desktop/UTM/CDE'
alias mc='cd /home/mira/Desktop/UTM/MMC'
alias mc2='cd /home/mira/Desktop/UTM/MMC2'
alias mc2l='cd /home/mira/Desktop/UTM/MMC2/labs'
alias op='cd /home/mira/Desktop/UTM/OOP'
alias opl='cd /home/mira/Desktop/UTM/OOP/labs'
alias ops='cd /home/mira/Desktop/UTM/OOP/sem'
alias o='xdg-open ./ &'
alias po='poweroff'
alias p='systemctl suspend'
alias jf='java -jar JFLAP7.0.jar &'
